# render.yaml

# O tipo de aplicativo que você está implantando
type: "node"

# O caminho para o arquivo principal do seu aplicativo
entrypoint: "src/index.js"

# A porta na qual o seu aplicativo estará ouvindo
port: 3000

# O plano gratuito do Render inclui até 550 horas de cálculo por mês
resources:
  memory: 256M
  cpu: 256m

# O plano gratuito do Render inclui até 10.000 requisições HTTP por hora
max_requests_per_hour: 10000

# O plano gratuito do Render inclui até 20 conexões de banco de dados por hora
max_connections_per_hour: 20
